name: stockly
description: "Stockly - store stock, inventory and sales in one simple app."

publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  flutter_riverpod: ^3.0.0
  image_picker: ^1.1.2
  mobile_scanner: ^7.0.1
  csv: ^6.0.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  cross_file: ^0.3.5
  excel: ^4.0.6
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/branding/logo.png"
  android: "ic_launcher"
  adaptive_icon_background: "assets/branding/logo_background.png"
  adaptive_icon_foreground: "assets/branding/logo_foreground.png"
  adaptive_icon_monochrome: "assets/branding/logo_monochrome.png"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    background_color: "#100E1A"
    theme_color: "#5B4CFF"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true

flutter:
  uses-material-design: true

